# -*- coding: utf-8 -*-
"""Mental Health Support Chatbot (Fine-Tuned).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wqBeCzr0x9iHnWQWTk3Nw74oTy0vYy96

1. Dataset Downloading ..
"""

from datasets import load_dataset
from transformers import AutoTokenizer

# 1. Load the dataset (works perfectly with datasets==2.19.1)
print("Downloading the dataset...")
dataset = load_dataset("empathetic_dialogues", trust_remote_code=True)
print("\nDataset details:")
print(dataset)

# 2. Load the tokenizer
model_name = "EleutherAI/gpt-neo-1.3B"
print(f"\nLoading the tokenizer: {model_name}...")
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Set the padding token (required for GPT models)
tokenizer.pad_token = tokenizer.eos_token

print("Dataset and Tokenizer loaded successfully!")

"""2. DATA-PREPROCESSING"""

# 1. Take a small subset of the data to prevent Colab from crashing
# We will use 5,000 examples for training and 500 for testing
small_train_dataset = dataset["train"].shuffle(seed=42).select(range(5000))
small_val_dataset = dataset["validation"].shuffle(seed=42).select(range(500))

# 2. Define a function to format and tokenize the conversation
def format_and_tokenize(example):
    # Creating a structured chat format
    # Using 'context' for emotion, 'prompt' for user situation, and 'utterance' for bot response
    chat_text = f"Emotion: {example['context']}\nUser: {example['prompt']}\nBot: {example['utterance']}{tokenizer.eos_token}"

    # Tokenizing the text (converting words to numbers for the AI)
    tokenized = tokenizer(chat_text, truncation=True, max_length=128, padding="max_length")

    # The model needs 'labels' to learn, which are the same as 'input_ids' for this task
    tokenized["labels"] = tokenized["input_ids"].copy()
    return tokenized

print("Processing and tokenizing the data...")

# 3. Apply the function to our datasets
tokenized_train = small_train_dataset.map(format_and_tokenize, batched=False)
tokenized_val = small_val_dataset.map(format_and_tokenize, batched=False)

print("Data processing complete! The data is now ready for the model.")

""" 3. MODEL-TRAINING"""

from transformers import AutoModelForCausalLM, TrainingArguments, Trainer
from peft import LoraConfig, get_peft_model, TaskType
import torch

# 1. Load the GPT-Neo Model
print("Loading the GPT-Neo 1.3B model...")
model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto")

# Resize token embeddings
model.resize_token_embeddings(len(tokenizer))

# -------------------------------------------------------------
# 2. THE MAGIC TRICK: Apply LoRA to save 99% Memory
# -------------------------------------------------------------
print("\nApplying LoRA (Parameter-Efficient Fine-Tuning)...")
peft_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    inference_mode=False,
    r=8,                     # Size of the adapter
    lora_alpha=32,
    lora_dropout=0.1
)

# Wrap the model
model = get_peft_model(model, peft_config)

# Print how many parameters we are actually training
model.print_trainable_parameters()

# Enable gradient checkpointing to save even more memory
model.gradient_checkpointing_enable()
# -------------------------------------------------------------

# 3. Set up Training Arguments
print("\nSetting up training parameters...")
training_args = TrainingArguments(
    output_dir="./empathetic-bot-results",
    eval_strategy="epoch",
    learning_rate=2e-4,             # LoRA requires a slightly higher learning rate
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=8,
    num_train_epochs=3,
    weight_decay=0.01,
    save_strategy="epoch",
    logging_steps=10,
    fp16=True,
    report_to="none"
)

# 4. Initialize the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val,
    processing_class=tokenizer,
)

# 5. Start the Training
print("\nStarting the training process...")
trainer.train()

print("\nTraining Finished Successfully!")

"""4. MODEL-TESTING"""

import torch

print("🤖 Mental Health Support Chatbot  is Ready!")
print("Type 'quit' or 'exit' to end the conversation.")
print("-" * 50)

# Set the model to evaluation mode
model.eval()

while True:
    user_input = input("You: ")

    if user_input.lower() in ['quit', 'exit']:
        print("Bot: Take care of yourself. Goodbye! 💙")
        break

    # Changed Emotion to 'caring' to get a warmer response
    prompt = f"Emotion: caring\nUser: {user_input}\nBot:"

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=60,
            temperature=0.6,           # Lowered slightly for more logical answers
            top_p=0.9,
            repetition_penalty=1.2,    # FIX 1: Stops the model from repeating the prompt
            no_repeat_ngram_size=2,    # FIX 2: Stops the model from looping the same sentence
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )

    full_response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    bot_reply = full_response.split("Bot:")[-1].strip()

    # FIX 3: Clean up the dataset's weird comma formatting
    bot_reply = bot_reply.replace("_comma_", ",")

    print(f"Bot: {bot_reply}")
    print("-" * 50)

